version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: home_cleaning_recipes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/  # Pour exécuter ton fichier ini.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Utilise le Dockerfile personnalisé
    container_name: php-web
    ports:
      - "80:80"  # Expose le port 80 pour localhost
    volumes:
      - ./code:/var/www/html  # Monte le dossier 'code' dans le conteneur pour Apache

volumes:
  db_data:  # Ceci définit le volume pour MySQL
