version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db-v2
    environment:
      MYSQL_ROOT_PASSWORD: CleaningPass!
      MYSQL_USER: EcoUser33
      MYSQL_PASSWORD: CleaningPass!
      MYSQL_DATABASE: home_cleaning_recipes
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-v2
    environment:
      PMA_HOST: mysql-db-v2
      MYSQL_ROOT_PASSWORD: CleaningPass!
      MYSQL_USER: EcoUser33
      MYSQL_PASSWORD: CleaningPass!
    ports:
      - "8080:80"

  web:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: php-web-v2
    ports:
      - "80:80"  
    volumes:
      - ./code:/var/www/html  

volumes:
  db_data: